apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # what the Ingress will use
      targetPort: 4499  # your pod’s containerPort
  type: ClusterIP
